### ISSUE TITLE
The eslint of this project is not working in vscode.

### ISSUE THREAD

**Issue by webcomeon** [antfu-collective/vitesse#532] opened 2024-04-25 15:23 UTC
I'm sorry, but I've tried for a long time and for some reason, ESLint doesn't work when using this project in vscode, and there is no automatic fix when saving.

**Comment by ZaneL1u** [comment] 2024-05-22 04:17
Delete eslint.options.extensions in the `User/settings.json`

从你的 ‼️**用户目录**‼️/settings.json 中，删除 eslint.options.extensions
在 MacOS 中，一般这个位置是

<img width="900" alt="image" src="https://github.com/antfu-collective/vitesse/assets/70258597/54b10a17-c794-49ce-b9d6-7821a6a0a71b">

**Comment by antfu** [comment] 2024-05-22 06:05
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-05-22 06:05 UTC
